templDir: templates
schemaURI: file://schemas

# Routes
routes:

# Hosts
- collection: /api/v1/hosts
  collectionPath: /host
  resource: /api/v1/hosts/{host}
  resourcePath: /host/{{.host}}
  dirName: hostname
  type: api
  schema: host.json

# Host Interfaces
- collection: /api/v1/hosts/{host}/interfaces
  collectionPath: /host/{{.host}}/interface
  resource: /api/v1/hosts/{host}/interfaces/{interface}
  resourcePath: /host/{{.host}}/interface/{{.interface}}
  dirName: interface
  type: api
  schema: interface.json

# Images
- collection: /api/v1/images
  collectionPath: /image
  resource: /api/v1/images/{image}
  resourcePath: /image/{{.image}}
  dirName: image
  type: api
  schema: image.json

# Image Versions
- collection: /api/v1/images/{image}/versions
  collectionPath: /image/{{.image}}/versions
  resource: /api/v1/images/{image}/versions/{version}
  resourcePath: /image/{{.image}}/versions/{{.version}}
  dirName: version
  type: api
  schema: image_version.json

# Hardware Addresses
- collection: /api/v1/hwaddr
  collectionPath: /hwaddr
  resource: /api/v1/hwaddr/{hwaddr}
  resourcePath: /hwaddr/{{.hwaddr}}
  dirName: hwaddr
  type: api
  schema: hwaddr.json

# Subnets
- collection: /api/v1/subnets
  collectionPath: /subnets
  resource: /api/v1/subnets/{subnet}
  resourcePath: /subnets/{{.subnet}}
  dirName: subnet
  type: api
  schema: subnet.json

# Sites
- collection: /api/v1/sites
  collectionPath: /sites
  resource: /api/v1/sites/{site}
  resourcePath: /sites/{{.site}}
  dirName: site
  type: api
  schema: site.json

# PXE Menu
- endpoint: /pxe/{hwaddr}
  type: template
  template: host

# JSON Schemas
- endpoint: /schemas
  type: static
  path: schemas

# Images
- endpoint: /images
  type: static
  path: images

# Scripts
- endpoint: /scripts
  type: static
  path: scripts
