api:
  image: mickep76/d2bsrv:0.1
  ports:
    - "8080:8080"
  links:
    - db:MONGO
data:
  image: mickep76/mongo-data
  command: tail -f /dev/null
  volumes:
    - /data/db
db:
  image: mongo
  volumes_from:
    - data
