api:
  image: dock2box/api:latest
  ports:
    - "8080:8080"
  links:
    - db:MONGO
data:
  image: dock2box/mongo-data:latest
  command: tail -f /dev/null
  volumes:
    - /data/db
db:
  image: mongo
  volumes_from:
    - data
